#!/usr/bin/env bash

set -e

export FPM_USER_ID=${FPM_USER_ID:-$(id -u)}
export FPM_GROUP_ID=${FPM_GROUP_ID:-$(id -g)}
export PHP_VERSION=${PHP_VERSION:-7.4}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

DOCK_COMPOSE_OPTIONS=" -p jelix-jcommunity-tests"

if [ "$JCOMMUNITY_WEB_PORT" == "" ]; then
  export JCOMMUNITY_WEB_PORT=8024
fi


if [ "$JCOMMUNITY_MYSQL_PORT" == "" ]; then
  export JCOMMUNITY_MYSQL_PORT=8549
fi

if [ "$JCOMMUNITY_PGSQL_PORT" == "" ]; then
  export JCOMMUNITY_PGSQL_PORT=8548
fi

if [ "$CMD" == "reset" ]; then
    # Stop/Remove containers
    docker compose $DOCK_COMPOSE_OPTIONS rm -sfv || true
    docker image rm jelix-jcommunity-tests_jcommunity_web || true
    docker image rm jelix-jcommunity-tests_jcommunity_php || true
    docker image rm jelix-jcommunity-tests_jcommunity_test_pgsql || true
    docker image rm jelix-jcommunity-tests_jcommunity_test_mysql || true

    # Clean database volume
    docker volume rm jcommunity_pg_data || true
    docker volume rm jcommunity_mysql_data || true

    sudo rm -rf $SCRIPTDIR/temp/*
    sudo rm -rf $SCRIPTDIR/var/log/*
    sudo rm -rf $SCRIPTDIR/var/db/*
    sudo rm -rf $SCRIPTDIR/vendor/*

    exit 0
fi


docker compose $DOCK_COMPOSE_OPTIONS $CMD
