#!/usr/bin/env bash

set -e

export FPM_USER_ID=${FPM_USER_ID:-$(id -u)}
export FPM_GROUP_ID=${FPM_GROUP_ID:-$(id -g)}
export PHP_VERSION=${PHP_VERSION:-7.4}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

if [ "$JCOMMUNITY_WEB_PORT" == "" ]; then
  export JCOMMUNITY_WEB_PORT=8024
fi


if [ "$JCOMMUNITY_MYSQL_PORT" == "" ]; then
  export JCOMMUNITY_MYSQL_PORT=8549
fi

if [ "$JCOMMUNITY_PGSQL_PORT" == "" ]; then
  export JCOMMUNITY_PGSQL_PORT=8548
fi

docker compose -p jelix-jcommunity-tests $CMD
